# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- sss_vue1.0

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  tagDate: $[ format('{0:yyyy}.{0:MM}.{0:dd}.{0:HH}.{0:mm}{0:ss}', pipeline.startTime) ]
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/sss_vue1.0')]
  
stages:
- stage: Build
  condition: and(succeeded(), eq(variables.isMain, 'true'))
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image and Push
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: | 
              latest
              $(tagDate)
        containerRegistry: DockerHub
        repository: dbcawa/gokart-sss-django
    - task: Docker@2
      displayName: Dev Build image and Push
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/dockerdev/Dockerfile'
        tags: | 
              gokart-sss-django_dev_latest
              gokart-sss-django_dev_$(tagDate)              
        containerRegistry: DockerHub
        repository: dbcawa/docker_app_dev    